version: "3"

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./../chat:/chat
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - mysql

  php:
    build:
      context: ./php
    container_name: php
    volumes:
      - ./../chat:/chat
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
  mysql:
    image: mysql:5.7.11
    container_name: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=root
      - MYSQL_USER=root
  phpmyadmin:
    depends_on:
      - mysql
    restart: always
    image: phpmyadmin/phpmyadmin:4.5.3.1-1
    container_name: phpmyadmin
    ports:
      - "8080:8080"
    links:
      - mysql
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
